spring:
  application:
    name: auth-service
    port: 8083

  logging:
    level:
      org:
        springframework:
          security: DEBUG

  ## DB Configuration ##
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentsystemdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  ## JPA / HIBERNATE  Configuration ##
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      ## jakarta:
        ## persistence:
          ## validation:
            ## mode: none

## Server Configuration ##
server:
  servlet:
    context-path: /api
  port: 8083

  ## JWT Configuration ##
jwt:
  jwtsecret: 2b44b0b00fd822d8ce753e54dac3dc4e06c2725f7db930f3b9924468b53194dbccdbe23d7baa5ef5fbc414ca4b2e64700bad60c5a7c45eaba56880985582fba4
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000

ahk-mail:
  email:
    username: isaac.goyette73@ethereal.email
    password: ${AUTH_SERVICE_EMAIL_PASSWORD}
    host: smtp.ethereal.email
    port: 587
    from: noreply@my-app.com
  client:
    host: http://localhost:5173
