server:
  port: 8761

eureka:
  client:
    register-with-eureka: false  # Kendini kaydetme (tek instance için)
    fetch-registry: false        # Registry'i çekme
    service-url:
      defaultZone: http://localhost:8761/eureka

spring: 
  zipkin:
    base-url: http://localhost:9411

management:
  tracing:
    sampling:
      probability: 1.0
