spring:
  application:
    name: keycloak-service
    port: 8084

  logging:
    level:
      org:
        springframework:
          security: DEBUG

  ## MYSQL DB Configuration ##
  datasource:
    url: jdbc:mysql://mysql:3306/keycloak?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
    username: keycloak
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  ## JPA / HIBERNATE  Configuration ##
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

## Server Configuration ##
server:
  port: 8084
