spring:
  application:
    name: keycloak-service
  logging:
    level:
      org:
        springframework:
          security: DEBUG
          
  ## MYSQL DB Configuration ##
  datasource:
    url: jdbc:mysql://localhost:3306/keycloak?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
    username: keycloak
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  ## JPA / HIBERNATE  Configuration ##
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  ## keycloak jwt
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/realm-ahk-dev/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/realms/realm-ahk-dev
          audience: ahk-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    
server:
  port: 8084
