spring:
  application:
    name: keycloak-service
    port: 8084

  logging:
    level:
      org:
        springframework:
          security: DEBUG

  ## DB Configuration ##
  datasource:
    url: jdbc:postgresql://localhost:5432/keycloak
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  ## JPA / HIBERNATE  Configuration ##
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      ## jakarta:
        ## persistence:
          ## validation:
            ## mode: none

## Server Configuration ##
server:
  port: 8084
