spring:
  application:
    name: property-service

  zipkin:
    base-url: http://localhost:9411

  datasource:
    url: jdbc:postgresql://localhost:5431/propertydb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

server:
  port: 8077

management:
  tracing:
    sampling:
      probability: 1.0
